spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  session:
    store-type: jdbc
  profiles:
    include: oauth
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.security: info
server:
  port: 8081
  servlet:
    encoding:
      force: true
  address: 0.0.0.0
springdoc:
  packages-to-scan: yerong.baedug
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui-baedug.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true

